### ISSUE TITLE
Getting CI faster

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#123]
**Is your feature request related to a problem? Please describe.**
The current CI pipeline is very slow. Mainly because it downloads Moddable SDK and ESP-IDF every time without making caches.

**Describe the solution you'd like**

- Use a CI-ready base image that includes Moddable SDK, ESP-IDF, and all the dependencies.
- Make a cache using `cache` action.

**Comment by stc1988** [comment]
> Make a cache using cache action.

Cache support for Moddable and ESP-IDF has been merged in #277. If there are no other suggestions for improvement, please proceed with closing it.

**Comment by meganetaaan** [comment]
Closing as completed. Thank you!
