### ISSUE TITLE
Moddable is old in Dockerfile

### ISSUE THREAD

**Issue by stc1988** [meganetaaan/stack-chan#126]
**Describe the bug**
Build application failed because Moddable is old.

**To Reproduce**

Using Docker images.

```
$ ./build-container.sh
$ ./launch-container.sh
# Run inside container
$ npm install

# run application
root@docker-desktop:/workspace/stackchan# mcconfig -d -m -p esp32/m5stack
### Error: '/root/Projects/moddable/examples/pins/audioout/resource-stream/manifest_streamer.json': manifest not found!
```

**Other**.
Git commit hash of Moddable in [Dockerfile](https://github.com/meganetaaan/stack-chan/blob/dev/v1.0/firmware/Dockerfile#L1) is old.

**Comment by meganetaaan** [comment]
Thank you for your report! I started fixing on [this](https://github.com/meganetaaan/stack-chan/tree/fix/container) branch.
As you pointed out the container image is too old to build the `dev/v1.0` Stack-chan.

I built a [docker image for the latest release (v3.7.0)](https://hub.docker.com/layers/meganetaaan/moddable-esp32/3.7.0/images/sha256-1431be80b42ea4bddd6305f5efedf14d1712660e15fa8443b97f4d0d65cea597?context=explore).
The Moddable tools (mcconfig, mcsim, etc.) works well. But when I try to run `npm run build` the container shows permission error. Still digging.
