### ISSUE TITLE
ファームウェアを転送した際の正しい挙動をドキュメントに入れる

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#133]
**既存の機能に問題がある場合、その説明**

ファームウェアをM5Stackに転送した際、どのような動作をすれば正しく動いているのかが判断できない。

**あなたが望む解決策**。

ファームウェアをM5Stackに転送した際の正しい挙動をドキュメントに入れる。
動画または画像付きが望ましい。

**Comment by washishi** [comment]
現状は「ファームウェア導入後、ｽﾀｯｸﾁｬﾝが左右に首振りを行うようであれば成功です。」
と書かれてますが現在のプログラム(ホスト)はボタンAを押すまでサーボは動かない様です
また動作時は左右に首振りではなくランダム動作の様です

**Comment by meganetaaan** [comment]
ランダムな動きではちゃんと動いているか分かりづらいので、テスト用ファームウェアを用意すべきな気がしますね🤔

**Comment by meganetaaan** [comment]
テスト用ファームウェアを更新して、A, B, Cボタンを押したときの挙動をドキュメントに追記しました。

https://github.com/meganetaaan/stack-chan/blob/dev/v1.0/firmware/docs/flashing-firmware_ja.md#%E5%9F%BA%E6%9C%AC%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%83%9B%E3%82%B9%E3%83%88%E3%81%AE%E6%9B%B8%E3%81%8D%E8%BE%BC%E3%81%BF
