### ISSUE TITLE
デバッグ方法の案内を載せる

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#134]
**既存の機能に問題がある場合、その説明**
デバッグ方法の案内がありません。package.jsonに`debug`コマンドはありますが使い方がドキュメントで示されていません。

**あなたが望む解決策**。
デバッグ方法をドキュメントに掲載します。

- コマンド
- xsbugの使い方概要
- 本家ドキュメントへのリンク

**Comment by stc1988** [comment]
本家の[ドキュメント](https://github.com/Moddable-OpenSource/moddable/blob/9ebf42f65103c35ce5beb4dc834403bacab602bd/documentation/xs/xsbug.md)です。

**Comment by meganetaaan** [comment]
https://github.com/meganetaaan/stack-chan/pull/226 で対応しました。
