### ISSUE TITLE
M5Stack BasicでVOICEVOXを使う場合、音声が遅くなる

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#156]
**不具合の概要**
M5Stack BasicでVOICEVOXを使う場合、音声がスロー再生したように遅くなる。

**再現手順**
不具合を再現できる手順を記述してください
1. 'mods/chatgpt`を手順に従いセットアップする
2. modを実行する
3. ｽﾀｯｸﾁｬﾝが喋るときの音声がスロー再生したように遅くなる。

**想定する挙動**
音声が通常の速度で再生される。

**環境 (次の項目を埋めてください):**

- OS: Ubuntu 20.04
- IDE: VSCode
- ｽﾀｯｸﾁｬﾝのバージョン： `dev/v1.0`最新（[19a69b2](https://github.com/meganetaaan/stack-chan/commit/19a69b2035c152898751180e6890caba898fd25b)）
- 使用するM5Stackの種類: M5Stack Basic（無印）

**その他**

esp-idfのv4系では再生速度まわりの挙動が変わってしまった。M5Stack公式ライブラリのM5Unifiedではクロック分周比の計算ロジックをライブラリ側に自前実装しているとのこと。

https://twitter.com/lovyan03/status/1645286458859884545

**Comment by meganetaaan** [comment]
M5Unifiedのクロック分周比の計算

https://github.com/m5stack/M5Unified/blob/master/src/utility/Speaker_Class.cpp#L110

**Comment by meganetaaan** [comment]
Moddable本家を確認したところ、esp-idf v5の対応が進んでおり、i2s周りについても修正のコミットがあるもよう。こちらをまず試す。

https://github.com/Moddable-OpenSource/moddable/compare/public...idf-v5

**Comment by stc1988** [comment]
@meganetaaan 

[fix/156/samplerate-for-voicevoxブランチ](https://github.com/meganetaaan/stack-chan/tree/fix/156/samplerate-for-voicevox) + Moddable最新を試しました。

https://github.com/meganetaaan/stack-chan/blob/fix/156/samplerate-for-voicevox/firmware/typings/wavstreamer.d.ts#L16
これが型定義エラーのため、任意パラメータに修正した上で、動作確認できました。

**Comment by meganetaaan** [comment]
型定義修正のpushが漏れていました。
動作確認ありがとうございます！PR作ります。

**Comment by meganetaaan** [comment]
暫定修正を取り込みました。しかし「M5Stack Basicで音声の再生速度が正しくない」という問題は残っています。
ModdableのESP-IDF v5対応の様子を見て、v5でも解決されていなければ別issueで管理しましょう。
