### ISSUE TITLE
M5Stack Core2 Microphone replace？Schematics have not found replace microphone

### ISSUE THREAD

**Issue by pickmonster100** [meganetaaan/stack-chan#193]
ご尽力と共有ありがとうございます。M5Stack Core2オリジナルの開発ソケット バージョンにはマイクがありましたが、オープンソース設計の PCB ボードに置き換えると、設計されたマイクがなくなりました。サウンドを録音するにはどうすればよいですか?

**Comment by meganetaaan** [comment]
試してくださりありがとうございます！
ご指摘の通りM5Stack Core2はボトム基板側にマイクがあるため、ｽﾀｯｸﾁｬﾝ基板を刺すとマイクが使えなくなります。
[pdmマイクユニット](https://www.switch-science.com/products/6620?_pos=2&_sid=38aeec5c3&_ss=r/)を別途刺して使うか、本体側にマイクが搭載されている[M5Stack CoreS3](https://www.switch-science.com/products/8960)をお使いいただく必要があります。

なお、本リポジトリのサンプルコードにはサウンド録音の機能はまだありませんのでご注意ください。
会話機能を試したい場合、 @robo8080 さんの「[AIｽﾀｯｸﾁｬﾝ](https://github.com/robo8080/AI_StackChan2)」でしたら本体のマイクを使った音声認識が可能です。
