### ISSUE TITLE
AIｽﾀｯｸﾁｬﾝ互換のAPIを実装する

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#204]
@robo8080 さんらが公開している[AIｽﾀｯｸﾁｬﾝ](https://github.com/robo8080/M5Unified_StackChan_ChatGPT)は、チャットや発話、APIキーの設定などができるWeb APIを備えています。これらのWeb API操作を簡単に行える[ｽﾀｯｸﾁｬﾝコンネクト](https://notes.yh1224.com/stackchan-connect/)などのアプリケーションもあります。

ししかわ版ｽﾀｯｸﾁｬﾝにもこれらのWeb APIを実装すれば、AIｽﾀｯｸﾁｬﾝと同じアプリケーションでやりとりできるようになります。

**Comment by ronron-gh** [comment]
motohです（その節はお世話になりました）。moddable版ｽﾀｯｸﾁｬﾝにWeb APIとWeb版VoiceVoxを追加実装して（ChatGPTはすでに実装されていた！）、初期AIｽﾀｯｸﾁｬﾝのようにスマホ越しで会話できるようになったので、いつかプルリクできればよいなと思っています（プルリクしたことがないため準備にもう少し時間がかかるかもしれません）。
Web APIの部分はmodにしています。modの名前はとりあえずai_stackchan_apiで考えています。

**Comment by stc1988** [comment]
https://github.com/meganetaaan/stack-chan/pull/235 にて基本機能は実装済みとなり、以下設定機能が未実装です。

* API設定
* ロール設定
* 音量設定

どれもHost側の拡張と合わせて検討した方がよさそうです。別途issueを起票しますので、本issueはクローズとしないでしょうか。

**Comment by meganetaaan** [comment]
そうですね。別issueで管理しましょう。
こちらはクローズします。
