### ISSUE TITLE
TTSの一部のインスタンス引数が意図せず必須になっている

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#281]
**不具合の概要**

[TTSVoicevox](https://github.com/stack-chan/stack-chan/blob/dev/v1.0/firmware/stackchan/speeches/tts-voicevox.ts)の一部のコンストラクタ引数が、実装では省略可能ですが、型定義では必須になっており、不整合が起きています。

-  `onPlayed` `onDone`: 省略時は何もしない
- `speakerId`: デフォルト値1
- `sampleRate`: デフォルト値11025

**修正案**

実装を正として型定義を修正します。
TTSの各実装でコンストラクタ引数のポリシー（変数名、必須かどうか）が共通になるようにチェックします。

**Comment by stc1988** [comment]
#282 で対応マージ済みですので、残課題なければクローズお願いします
