### ISSUE TITLE
pre-commitフックでlintとformatをかける

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#301]
**既存の機能に問題がある場合、その説明**
lint/formatをかけないままpushしてしまい、CIに失敗することが多いです

**あなたが望む解決策**。
pre-commitフックを導入してコミット前にlint/formatがかかるようにします。

- フックの実行が開発を妨げるほど遅くないこと
- オプトイン、オプトアウトが簡単にできること

フックの管理は[husky](https://typicode.github.io/husky/)が簡単で良さそうです。

**Comment by stc1988** [comment]
私も度々やってしまうので導入および方針について賛成です 🙆‍♂️ 

あと別観点のアイデアだと、actionsに[concurrency](https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs)を設定することで、PR後pushするたびにCIが多重に起動するのを抑制するのも導入した方がよいかもしれません

**Comment by meganetaaan** [comment]
対応済みのためクローズします。
