### ISSUE TITLE
Webブラウザからの書き込みを行ったが顔が表示されるだけで動かない

### ISSUE THREAD

**Issue by Ayumu999** [meganetaaan/stack-chan#308]
**不具合の概要**
20241227ｽﾀｯｸﾁｬﾝアールティ版完成品(M5stack CoreS3)を購入。
プログラムから書き込みでエラー無く進んだが、表情が表示されるのみで動きがなかったためリセットボタン長押し(緑色に点灯するまで)をし、Webブラウザからの書き込みを試しに行ったが同様に顔が表示されるのみで動きがない。

**再現手順**
1.https://rt-net.github.io/stack-chan/web/flash/　にアクセス(GoogleChrome)
2.M5Stack CoreS3を選択
3.ｽﾀｯｸﾁｬﾝとPCを接続(付属ケーブルにて)
4.ｽﾀｯｸﾁｬﾝのスライドスイッチを上にあげ電源をいれる(手順説明には電源ボタンを押すように書いてあるがスライドを上にあげた時点で電源が入っている)
5.Flash Stack-chan farmwareボタンを押下
6.接続要求の中からｽﾀｯｸﾁｬﾝを選択
7.INSTALL STACK-CHANを押下
8.インストールが完了し、Completeウィンドウで「Next」ボタン押下
9.ｽﾀｯｸﾁｬﾝからケーブルを外す
10.変化がないのでｽﾀｯｸﾁｬﾝを再起動

**想定する挙動**
表情の変化や動きがある(？)

**環境 (次の項目を埋めてください):**

- OS: Windows11 Home　バージョン	23H2
- 使用するM5Stackの種類　M5Stack CoreS3

**その他**

**Comment by stc1988** [comment]
https://rt-net.github.io/stack-chan/web/flash/ から書き込んだのであれば、本リポジトリではなく、[アールティ版のリポジトリ](https://github.com/rt-net/stack-chan)　の方でissueを作成された方がよいかと思います。

#307 にある通り、本リポジトリのファームウェアではアールティ版のサーボモータが動作しないのが現状になります。
