### ISSUE TITLE
Buttons not working on Core2. No reaction to button clicks

### ISSUE THREAD

**Issue by SteveJos** [meganetaaan/stack-chan#36]
Since the stack-chan is now happily working on the newer Core2 it would be great to also use the touch buttons.
Unfortunately there is no reaction on the display while touching the buttons.

Thank you!

**Comment by meganetaaan** [comment]
Sorry for my late response!
Buttons of Core2 are currently not supported by ModdableSDK. I will try implementing them on Stack-chan side.

**Comment by meganetaaan** [comment]
I added virtual buttons for Core2. They work just the same as physical buttons of M5Stack Basic. Enjoy!
If you find another problem about it. Feel free to reopen the issue.
