### ISSUE TITLE
Tiltの稼働範囲が大きすぎる

### ISSUE THREAD

**Issue by mongonta0716** [meganetaaan/stack-chan#54]
**不具合の概要**
Tiltの稼働範囲が大きすぎる

**再現手順**
通常の手順で実行するだけです。

**想定する挙動**
サーボが稼働範囲を超えて稼働します。

https://github.com/meganetaaan/stack-chan/blob/main/firmware/stackchan/sg90-driver.ts#L70

**Comment by meganetaaan** [comment]
上下に関して上方向に25度、下方向に10度まで制限しました！
