### ISSUE TITLE
possible issue pinning tilt angle in rs30x

### ISSUE THREAD

**Issue by phoddie** [meganetaaan/stack-chan#56]
I have recently had the pleasure of exploring the Stack-chan implementation by running it on the Stack-chan hardware! I don't know much about robotics, so I'm not sure about this issue.

I was exploring how to use the motors to have Stack-chan look side-to-side and up-and-down. Using the `yaw` to control side-to-side works well:

```js
robot._driver.applyPose({yaw: Math.PI / 3, pitch: 0});
robot._driver.applyPose({yaw: -Math.PI / 3, pitch: 0});
```

However, using the `pitch` to control up-and-down did not move the motors much, if at all.

```js
robot._driver.applyPose({yaw: 0, pitch: 0.43});
robot._driver.applyPose({yaw: 0, pitch: -0.17});
```

Eventually, I noticed this line in the RS30X driver:

https://github.com/meganetaaan/stack-chan/blob/168622e4905e027cdd6cc8e5e19553676ff59ba2/firmware/stackchan/rs30x-driver.ts#L27

This expression always evaluates to 10 in my tests. As an experiment, I changed it to the following:

```js
    let tiltAngle = -pose.pitch * 180 / Math.PI;
    if (tiltAngle < -25)
      tiltAngle = -25;
    else if (tiltAngle > 10)
      tiltAngle = 10;
```

I'm not sure whether I'm using the APIs incorrectly or if there is a mistake in the code that pins `tiltAngle`.

**Comment by meganetaaan** [comment]
Hello @phoddie. Thank you for getting and exploring Stack-chan!
This was definitely a bug which I made in my latest commits.
Now I've fixed in https://github.com/meganetaaan/stack-chan/pull/57. Could you try it?

**Comment by phoddie** [comment]
Thank you for the very quick response and fix! The change appears correct. Unfortunately, my Stack-chan is visiting San Jose for a few days, so I cannot try running the change for a little while.

**Comment by phoddie** [comment]
Just to confirm, today I verified that the fix works as expected. Thanks again.

By the way, I noticed that I have a few changes to stackchan/manifest.json that might be useful. What is the best way to share that? For example, I can open an issue with some suggestions. Please let me know.

**Comment by meganetaaan** [comment]
@phoddie 
I'm happy to hear the fix works.

>By the way, I noticed that I have a few changes to stackchan/manifest.json that might be useful. What is the best way to share that? For example, I can open an issue with some suggestions. Please let me know.

Would you like to open an issue for your suggestions? Thank you!
