### ISSUE TITLE
SG-90 case broken when inserting servo

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#7]
https://twitter.com/shikarunochi/status/1419838804064575493

組み立て中にブラケットのサーボに当たる部分が折れてしまったようです。

* 元ツイートにあるように、この箇所を水平にしてプリントするよう注記を加える
* モデルを修正（この箇所を補強する）

のいずれか対策したいと思います。

--

It looks like the part of the bracket that hits the servo broke off during assembly.

So I would like to:

- Add a note to print the model on this part horizontal, as written in the original tweet.
- Modify the model (reinforce the broken part of the model)

**Comment by tomorrow56** [comment]
すみません。お手数かけます

2021年7月27日(火) 13:06 Shinya Ishikawa ***@***.***>:

**Comment by meganetaaan** [comment]
次のPRで該当部分が補強されました。
The weak point is made thick by the PR below.

https://github.com/meganetaaan/stack-chan/pull/9
