### ISSUE TITLE
NL27WZ125 is discontinued

### ISSUE THREAD

**Issue by meganetaaan** [meganetaaan/stack-chan#79]
**Describe the bug**
NL27WZ125 is discontinued. We should find an alternative.

https://www.digikey.jp/ja/products/detail/onsemi/NL27WZ125USG/661486

**Comment by washishi** [comment]
TC7WH241FK もメーカーページで出てこない様なのでディスコンかも

TC7WH125FK が使えそう
https://toshiba.semicon-storage.com/jp/semiconductor/product/general-purpose-logic-ics/detail.TC7WH125FK.html

鈴商で扱っているよう(10個セット200円 + 送料・・・)
https://suzushoweb.shop-pro.jp/?pid=101173315
鈴商 昔は秋葉に店舗あったんだけどなぁ・・・

**Comment by meganetaaan** [comment]
新基板では3ステートバッファの代わりにRS485のICを採用したため、こちらの問題は解消されました。

---

In the new circuit board, we replaced the 3-state buffer with an RS485 IC, resolving the issue.
